export default {
  regular: {
    akuoumaru: require("./regular/Akuoumaru.png"),
    alleyhunter: require("./regular/AlleyHunter.png"),
    amenomakageuchi: require("./regular/AmenomaKageuchi.png"),
    amosbow: require("./regular/AmosBow.png"),
    aquilafavonia: require("./regular/AquilaFavonia.png"),
    blackcliffagate: require("./regular/BlackcliffAgate.png"),
    blackclifflongsword: require("./regular/BlackcliffLongsword.png"),
    blackcliffpole: require("./regular/BlackcliffPole.png"),
    blackcliffslasher: require("./regular/BlackcliffSlasher.png"),
    blackcliffwarbow: require("./regular/BlackcliffWarbow.png"),
    blacktassel: require("./regular/BlackTassel.png"),
    bloodtaintedgreatsword: require("./regular/BloodtaintedGreatsword.png"),
    calamityqueller: require("./regular/CalamityQueller.png"),
    cinnabarspindle: require("./regular/CinnabarSpindle.png"),
    compoundbow: require("./regular/CompoundBow.png"),
    coolsteel: require("./regular/CoolSteel.png"),
    crescentpike: require("./regular/CrescentPike.png"),
    darkironsword: require("./regular/DarkIronSword.png"),
    deathmatch: require("./regular/Deathmatch.png"),
    debateclub: require("./regular/DebateClub.png"),
    dodocotales: require("./regular/DodocoTales.png"),
    dragonsbane: require("./regular/DragonsBane.png"),
    dragonspinespear: require("./regular/DragonspineSpear.png"),
    elegyfortheend: require("./regular/ElegyfortheEnd.png"),
    emeraldorb: require("./regular/EmeraldOrb.png"),
    engulfinglightning: require("./regular/EngulfingLightning.png"),
    everlastingmoonglow: require("./regular/EverlastingMoonglow.png"),
    eyeofperception: require("./regular/EyeofPerception.png"),
    favoniuscodex: require("./regular/FavoniusCodex.png"),
    favoniusgreatsword: require("./regular/FavoniusGreatsword.png"),
    favoniuslance: require("./regular/FavoniusLance.png"),
    favoniussword: require("./regular/FavoniusSword.png"),
    favoniuswarbow: require("./regular/FavoniusWarbow.png"),
    ferrousshadow: require("./regular/FerrousShadow.png"),
    festeringdesire: require("./regular/FesteringDesire.png"),
    filletblade: require("./regular/FilletBlade.png"),
    freedomsworn: require("./regular/FreedomSworn.png"),
    frostbearer: require("./regular/Frostbearer.png"),
    hakushinring: require("./regular/HakushinRing.png"),
    halberd: require("./regular/Halberd.png"),
    hamayumi: require("./regular/Hamayumi.png"),
    harbingerofdawn: require("./regular/HarbingerofDawn.png"),
    ironsting: require("./regular/IronSting.png"),
    katsuragikirinagamasa: require("./regular/KatsuragikiriNagamasa.png"),
    kitaincrossspear: require("./regular/KitainCrossSpear.png"),
    lionsroar: require("./regular/LionsRoar.png"),
    lithicblade: require("./regular/LithicBlade.png"),
    lithicspear: require("./regular/LithicSpear.png"),
    lostprayertothesacredwinds: require("./regular/LostPrayertotheSacredWinds.png"),
    luxurioussealord: require("./regular/LuxuriousSeaLord.png"),
    magicguide: require("./regular/MagicGuide.png"),
    mappamare: require("./regular/MappaMare.png"),
    memoryofdust: require("./regular/MemoryofDust.png"),
    messenger: require("./regular/Messenger.png"),
    mistsplitterreforged: require("./regular/MistsplitterReforged.png"),
    mitternachtswaltz: require("./regular/MitternachtsWaltz.png"),
    mouunsmoon: require("./regular/MouunsMoon.png"),
    otherworldlystory: require("./regular/OtherworldlyStory.png"),
    polarstar: require("./regular/PolarStar.png"),
    predator: require("./regular/Predator.png"),
    primordialjadecutter: require("./regular/PrimordialJadeCutter.png"),
    primordialjadewingedspear: require("./regular/PrimordialJadeWingedSpear.png"),
    prototypeamber: require("./regular/PrototypeAmber.png"),
    prototypearchaic: require("./regular/PrototypeArchaic.png"),
    prototypecrescent: require("./regular/PrototypeCrescent.png"),
    prototyperancour: require("./regular/PrototypeRancour.png"),
    prototypestarglitter: require("./regular/PrototypeStarglitter.png"),
    rainslasher: require("./regular/Rainslasher.png"),
    ravenbow: require("./regular/RavenBow.png"),
    recurvebow: require("./regular/RecurveBow.png"),
    redhornstonethresher: require("./regular/RedhornStonethresher.png"),
    royalbow: require("./regular/RoyalBow.png"),
    royalgreatsword: require("./regular/RoyalGreatsword.png"),
    royalgrimoire: require("./regular/RoyalGrimoire.png"),
    royallongsword: require("./regular/RoyalLongsword.png"),
    royalspear: require("./regular/RoyalSpear.png"),
    rust: require("./regular/Rust.png"),
    sacrificialbow: require("./regular/SacrificialBow.png"),
    sacrificialfragments: require("./regular/SacrificialFragments.png"),
    sacrificialgreatsword: require("./regular/SacrificialGreatsword.png"),
    sacrificialsword: require("./regular/SacrificialSword.png"),
    serpentspine: require("./regular/SerpentSpine.png"),
    sharpshootersoath: require("./regular/SharpshootersOath.png"),
    skyridergreatsword: require("./regular/SkyriderGreatsword.png"),
    skyridersword: require("./regular/SkyriderSword.png"),
    skywardatlas: require("./regular/SkywardAtlas.png"),
    skywardblade: require("./regular/SkywardBlade.png"),
    skywardharp: require("./regular/SkywardHarp.png"),
    skywardpride: require("./regular/SkywardPride.png"),
    skywardspine: require("./regular/SkywardSpine.png"),
    slingshot: require("./regular/Slingshot.png"),
    snowtombedstarsilver: require("./regular/SnowTombedStarsilver.png"),
    solarpearl: require("./regular/SolarPearl.png"),
    songofbrokenpines: require("./regular/SongofBrokenPines.png"),
    staffofhoma: require("./regular/StaffofHoma.png"),
    summitshaper: require("./regular/SummitShaper.png"),
    swordofdescension: require("./regular/SwordofDescension.png"),
    thealleyflash: require("./regular/TheAlleyFlash.png"),
    thebell: require("./regular/TheBell.png"),
    theblacksword: require("./regular/TheBlackSword.png"),
    thecatch: require("./regular/TheCatch.png"),
    theflute: require("./regular/TheFlute.png"),
    thestringless: require("./regular/TheStringless.png"),
    theunforged: require("./regular/TheUnforged.png"),
    theviridescenthunt: require("./regular/TheViridescentHunt.png"),
    thewidsith: require("./regular/TheWidsith.png"),
    thrillingtalesofdragonslayers: require("./regular/ThrillingTalesofDragonSlayers.png"),
    thunderingpulse: require("./regular/ThunderingPulse.png"),
    travelershandysword: require("./regular/TravelersHandySword.png"),
    twinnephrite: require("./regular/TwinNephrite.png"),
    vortexvanquisher: require("./regular/VortexVanquisher.png"),
    wavebreakersfin: require("./regular/WavebreakersFin.png"),
    whiteblind: require("./regular/Whiteblind.png"),
    whiteirongreatsword: require("./regular/WhiteIronGreatsword.png"),
    whitetassel: require("./regular/WhiteTassel.png"),
    windblumeode: require("./regular/WindblumeOde.png"),
    wineandsong: require("./regular/WineandSong.png"),
    wolfsgravestone: require("./regular/WolfsGravestone.png"),
  },
};
export const types = [
  {
    name: "bow",
    image: require("./type/bow.png"),
  },
  {
    name: "catalyst",
    image: require("./type/catalyst.png"),
  },
  {
    name: "claymore",
    image: require("./type/claymore.png"),
  },
  {
    name: "polearm",
    image: require("./type/polearm.png"),
  },
  {
    name: "sword",
    image: require("./type/sword.png"),
  },
];
